apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: advent-back-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advent-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advent-back
  template:
    metadata:
      labels:
        app: advent-back
    spec:
      containers:
        - name: back
          image: advent_calendar-back:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            volumeMounts:
            - name: data
              mountPath: /app/database.db
              subPath: database.db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: advent-back-data
---
apiVersion: v1
kind: Service
metadata:
  name: advent-back
spec:
  selector:
    app: advent-back
  ports:
    - port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advent-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advent-front
  template:
    metadata:
      labels:
        app: advent-front
    spec:
      containers:
        - name: front
          image: advent_calendar-front:latest
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: http://advent-back:3001
---
apiVersion: v1
kind: Service
metadata:
  name: advent-front
spec:
  type: LoadBalancer
  selector:
    app: advent-front
  ports:
    - port: 80
      targetPort: 80
